version: '3.9'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: djangok8
    environment:
      - PORT=8020
    env_file:
      - web/.env
    ports: [8001:8020]